import { useEffect, useMemo, useState } from 'react';
import type { DreamerProject, GenerateSettings, RuntimeStatus } from '../shared/types';

const defaults:GenerateSettings={modelId:'qwen-image-2.1-q4km',seed:42,steps:28,cfgScale:6,width:1024,height:1024,offloadToCpu:true};

export function App(){
  const [project,setProject]=useState<DreamerProject|null>(null),[runtime,setRuntime]=useState<RuntimeStatus|null>(null),[instruction,setInstruction]=useState(''),[settings,setSettings]=useState(defaults),[busy,setBusy]=useState(false),[modelBusy,setModelBusy]=useState(false),[message,setMessage]=useState('Create a project, import an image, then describe one small change.'),[preview,setPreview]=useState<string|null>(null);
  useEffect(()=>{window.nexusDreamer.runtime().then(setRuntime);return window.nexusDreamer.onEvent(event=>{if(event.type==='run.progress'){const p=event.payload as {current:number;total:number};setMessage(`Generating ${p.current}/${p.total}`);}if(event.type==='model.download-progress'){const p=event.payload as {filename:string;received:number;total?:number};setMessage(`Downloading ${p.filename}${p.total?' '+Math.floor(p.received/p.total*100)+'%':''}`);}});},[]);
  const chain=project?project.chains[project.activeChainId]:null,head=chain&&project?project.steps[chain.headStepId]:null,ordered=useMemo(()=>project?Object.values(project.steps).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)):[],[project]);
  useEffect(()=>{const aid=head?(head.outputArtifactId??head.inputArtifactId):null,artifact=aid&&project?project.artifacts[aid]:null;if(!artifact){setPreview(null);return;}window.nexusDreamer.imageData(artifact.path).then(setPreview).catch(()=>setPreview(null));},[project,head?.id,head?.outputArtifactId]);
  async function createProject(){const r=await window.nexusDreamer.execute({type:'project.create',name:'New Dream'});if(r.ok)setProject(r.data as DreamerProject);else setMessage(r.error??'Failed');}
  async function importImage(){if(!project)return;const sourcePath=await window.nexusDreamer.pickImage();if(!sourcePath)return;const r=await window.nexusDreamer.execute({type:'image.import',projectId:project.id,sourcePath});if(r.ok)setProject(r.data as DreamerProject);else setMessage(r.error??'Import failed');}
  async function generate(){if(!project||!chain||!instruction.trim())return;setBusy(true);const a=await window.nexusDreamer.execute({type:'chain.append-edit',projectId:project.id,chainId:chain.id,instruction,settings});if(!a.ok){setMessage(a.error??'Failed');setBusy(false);return;}const next=a.data as {project:DreamerProject;step:{id:string}};setProject(next.project);const r=await window.nexusDreamer.execute({type:'step.run',projectId:project.id,stepId:next.step.id});setBusy(false);if(!r.ok)setMessage(r.error??'Generation failed');else{setProject((r.data as {project:DreamerProject}).project);setInstruction('');setMessage('Result ready. Accept it to advance the chain.');}}
  async function accept(stepId:string,runId:string){if(!project)return;const r=await window.nexusDreamer.execute({type:'step.accept',projectId:project.id,stepId,runId});if(r.ok){setProject(r.data as DreamerProject);setMessage('Accepted. This result is now the next input.');}}
  async function reject(stepId:string){if(!project)return;const r=await window.nexusDreamer.execute({type:'step.reject',projectId:project.id,stepId});if(r.ok){setProject(r.data as DreamerProject);setMessage('Rejected. The accepted chain head is unchanged.');}}
  async function installModel(){setModelBusy(true);const r=await window.nexusDreamer.execute({type:'model.install',modelId:defaults.modelId});setModelBusy(false);if(!r.ok)setMessage(r.error??'Model download failed');else{setRuntime(await window.nexusDreamer.runtime());setMessage('Model bundle installed.');}}
  const review=ordered.filter(s=>s.status==='review').at(-1);

  return <div className="app"><header><div><b>NEXUS</b><span>DREAMER</span></div><small>CHAIN HARNESS · LOCAL FIRST</small></header><main>
    <aside className="rail"><h3>PROJECT</h3>{!project?<button onClick={createProject}>New Project</button>:<><strong>{project.name}</strong><button onClick={importImage}>Import Image</button><h3>CHAIN</h3>{ordered.map((s,i)=><div className={'step '+(head?.id===s.id?'active':'')} key={s.id}><span>{String(i).padStart(2,'0')}</span><div><b>{s.status}</b><small>{s.instruction}</small></div></div>)}</>}</aside>
    <section className="canvas"><div className="frame">{head?<>{preview?<img className="preview" src={preview} alt="Active revision"/>:<div className="orb">◌</div>}<div className="caption"><h2>{head.instruction}</h2><p>{(head.outputArtifactId??head.inputArtifactId).slice(0,24)}…</p></div></>:<><div className="orb">✦</div><h2>Start with an image</h2><p>Accepted results become immutable revisions.</p></>}</div><footer>{message}</footer></section>
    <aside className="panel"><h3>NEXT CHANGE</h3><textarea value={instruction} onChange={e=>setInstruction(e.target.value)} placeholder="Add a tiny gold buckle to the belt…"/><label>Steps<input type="number" value={settings.steps} onChange={e=>setSettings({...settings,steps:+e.target.value})}/></label><label>CFG<input type="number" step="0.5" value={settings.cfgScale} onChange={e=>setSettings({...settings,cfgScale:+e.target.value})}/></label><label>Seed<input type="number" value={settings.seed} onChange={e=>setSettings({...settings,seed:+e.target.value})}/></label><button className="primary" disabled={!head||busy||!instruction.trim()} onClick={generate}>{busy?'Running…':'Generate Next Step'}</button>{review&&<div className="review"><button onClick={()=>accept(review.id,review.runIds.at(-1)!)}>Accept</button><button onClick={()=>reject(review.id)}>Reject</button></div>}<div className="runtime"><h3>RUNTIME</h3><span>{runtime?.platform} · {runtime?.arch}</span><span>{runtime?.totalMemoryGb} GB RAM</span><span className={runtime?.backendReady?'ok':'warn'}>{runtime?.backendReady?'Backend ready':'Set NEXUS_DREAMER_SD_CLI'}</span><span className={runtime?.modelReady?'ok':'warn'}>{runtime?.modelReady?'Model ready':(runtime?.modelIssues.length??0)+' model files missing'}</span>{runtime&&!runtime.modelReady&&<button disabled={modelBusy} onClick={installModel}>{modelBusy?'Downloading…':'Download Model Bundle'}</button>}</div></aside>
  </main></div>;
}
